// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPLof4naFMDV7nN71pkxyMuJP5LbZQCkM',
    appId: '1:627677212354:web:f7c39da988000929bed55b',
    messagingSenderId: '627677212354',
    projectId: 'turun-7d6d0',
    authDomain: 'turun-7d6d0.firebaseapp.com',
    storageBucket: 'turun-7d6d0.firebasestorage.app',
    measurementId: 'G-PVTMVKVDDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrUKcP3fe7yEbI-5woT7mS367WmLRirpI',
    appId: '1:627677212354:android:08479e2c1187f1b1bed55b',
    messagingSenderId: '627677212354',
    projectId: 'turun-7d6d0',
    storageBucket: 'turun-7d6d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJRxzHlNMC0zIvOntIVN_WhRGg3OoewUY',
    appId: '1:627677212354:ios:7e39ccc4abcf70bbbed55b',
    messagingSenderId: '627677212354',
    projectId: 'turun-7d6d0',
    storageBucket: 'turun-7d6d0.firebasestorage.app',
    iosBundleId: 'com.tehobenk.turun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJRxzHlNMC0zIvOntIVN_WhRGg3OoewUY',
    appId: '1:627677212354:ios:7e39ccc4abcf70bbbed55b',
    messagingSenderId: '627677212354',
    projectId: 'turun-7d6d0',
    storageBucket: 'turun-7d6d0.firebasestorage.app',
    iosBundleId: 'com.tehobenk.turun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPLof4naFMDV7nN71pkxyMuJP5LbZQCkM',
    appId: '1:627677212354:web:a3945669a77fd863bed55b',
    messagingSenderId: '627677212354',
    projectId: 'turun-7d6d0',
    authDomain: 'turun-7d6d0.firebaseapp.com',
    storageBucket: 'turun-7d6d0.firebasestorage.app',
    measurementId: 'G-49CTGE3JG1',
  );
}
